/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_TempMeter
#define HEADER_TempMeter

#include "Meter.h"

extern int TempMeter_attributes[];

extern MeterClass TempMeter_class;

#endif
